### ISSUE TITLE
Кнопка удаления оповещения

### ISSUE THREAD

**Issue by vozzurg** [Forden/zukuzuku-bot#5]
**Проблема:** при /report сообщение о жалобе отправляется всем админам и модераторам, которых может быть 10-15. Один обработал, остальные натыкаются на оповещение.
**Решение:** кнопка удаления оповещения, которая удалит оповещение у всех остальных админов/модераторов, и выведет в сообщение о репорте "_Спасибо, мы обработаем ваше обращение._"дополнительную строчку "%username% обработал вашу жалобу"

**Comment by Forden** [comment]
Будет реализовано через создание отдельного лог-канала, в который будет скидывать репорт с пином со звуком.

**Comment by Forden** [comment]
Завершено.
